name: example
on:
  schedule:
    - cron: '*/1 * * * *' # Every 5 minutes
jobs:
  job:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - name: Check Tickets
        uses: mooyoul/melon-ticket-actions@v1.1.0
        with:
          product-id: 211062
          schedule-id: 100001
          seat-id: A,B,C,D,E,J,K
          message: '<@U12345678> 달려달려~'
on:
      failure:
        - name: Notify on failure
          run: echo "Job failed"
      success:
        - name: Notify on success
          run: echo "Job succeeded"
